// <auto-generated />
using System;
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230908135822_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC.Models.Disaster", b =>
                {
                    b.Property<int>("disasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("disasterId"), 1L, 1);

                    b.Property<string>("aidType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disasterDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disasterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("disasterId");

                    b.ToTable("Disasters");
                });

            modelBuilder.Entity("MVC.Models.GoodsDonation", b =>
                {
                    b.Property<int>("goodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("goodsId"), 1L, 1);

                    b.Property<DateTime>("donationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("donatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodsCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("goodsDescription")
                        .HasColumnType("int");

                    b.Property<int>("numberOfItems")
                        .HasColumnType("int");

                    b.HasKey("goodsId");

                    b.ToTable("goodDonation");
                });

            modelBuilder.Entity("MVC.Models.MonetaryDonation", b =>
                {
                    b.Property<int>("moneyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("moneyId"), 1L, 1);

                    b.Property<DateTime>("donationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("donatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moneyAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("moneyId");

                    b.ToTable("monetaryGoods");
                });
#pragma warning restore 612, 618
        }
    }
}
